package com.example.demo.User;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;


@Entity //this is for hybernate
@Table(name = "users") // this is for the table in the db 
// the "user" keyword is resereved and need to be changed -> users
public class User {


    @Id
    @SequenceGenerator(
        name = "user_Sequence",
        sequenceName = "user_Sequence",
        allocationSize = 1
    )
    @GeneratedValue(
        strategy = GenerationType.SEQUENCE,
        generator = "user_Sequence"
    )
    
    private Long id;
    private String username;
    private String password;
    private String role; // e.g., Admin, Employee
    private String branch;

    // Empty Constructor
    public User() {
    }
    // Full Constructor
    public User(Long id, String username, String password, String role, String branch) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.role = role;
        this.branch = branch;
    }

    // Constructor without id (generated by DB)
    public User(String username, String password, String role, String branch) {
        this.username = username;
        this.password = password;
        this.role = role;
        this.branch = branch;
    }

    // Getters
    public Long getId() {
        return id;
    }
    public String getUsername() {
        return username;
    }

    public String getPassword() {
        return password;
    }

    public String getRole() {
        return role;
    }

    public String getBranch() {
        return branch;
    }

    void setUsername(String username) {
        this.username = username;
    }

    void setPassword(String password) {
        this.password = password;
    }

    void setRole(String role) {
        this.role = role;
    }

    void setBranch(String branch) {
        this.branch = branch;
    }
    @Override
    public String toString() {
        return "{" +
            " id='" + getId() + "'" +
            ", username='" + getUsername() + "'" +
            ", password='" + getPassword() + "'" +
            ", role='" + getRole() + "'" +
            ", branch='" + getBranch() + "'" +
            "}";
    }
}